{{ if not .Values.existingSecret }}
{{ if .Values.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dyndns-chart.fullname" . }}
data:
{{- range $key, $value := .Values.envSecrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{ end }}
{{ end }}