{{- if not .Values.postgres.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "affine.fullname" . }}-postgres
  labels:
    {{- include "affine.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ default "affine" .Values.postgres.auth.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ required "A valid .Values.postgres.auth.password is required!" .Values.postgres.auth.password | b64enc | quote }}
  POSTGRES_DB: {{ default "affine" .Values.postgres.auth.database | b64enc | quote }}
  POSTGRES_HOST: {{ include "affine.fullname" . }}-postgres
{{- end }}
