apiVersion: v1
kind: Service
metadata:
  name: {{ include "affine.fullname" . }}-redis
  labels:
    {{- include "affine.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
